apiVersion: v1
kind: Secret
metadata: 
  name: chatapp-secret
  namespace: chat-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:chatapp123@postgres-service:5432/chatapp?schema=public"
  POSTGRES_PASSWORD: "chatapp123"
  AUTH_SECRET: "vOUAtGRMMHN7U2sL3hO9Xj0gM6MEFI9ZiIS8iobs8DqeLjkCqAr19F583EecsGFty3XIeH87hGxBgMo5KZ+7ig=="